# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_email_verified', models.BooleanField(default=False)),
                ('email_verification_code', models.UUIDField(default=uuid.uuid4, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
